version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: user_balance_postgres_dev
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: user_balance_app_dev
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres_data:
