// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	Balance float32 `json:"balance"`
	UserId  int     `json:"userId"`
}

// DepositRequest defines model for DepositRequest.
type DepositRequest struct {
	Amount float32 `json:"amount"`
	UserId int     `json:"userId"`
}

// DepositResponse defines model for DepositResponse.
type DepositResponse struct {
	Balance float32 `json:"balance"`
	UserId  int     `json:"userId"`
}

// ReserveRequest defines model for ReserveRequest.
type ReserveRequest struct {
	Amount    float32 `json:"amount"`
	ServiceId int     `json:"serviceId"`
	UserId    int     `json:"userId"`
}

// SendRequest defines model for SendRequest.
type SendRequest struct {
	Amount     float32 `json:"amount"`
	FromUserId int     `json:"fromUserId"`
	ToUserId   int     `json:"toUserId"`
}

// PostApiV1BalanceDepositJSONRequestBody defines body for PostApiV1BalanceDeposit for application/json ContentType.
type PostApiV1BalanceDepositJSONRequestBody = DepositRequest

// PostApiV1BalanceReserveJSONRequestBody defines body for PostApiV1BalanceReserve for application/json ContentType.
type PostApiV1BalanceReserveJSONRequestBody = ReserveRequest

// PostApiV1BalanceSendJSONRequestBody defines body for PostApiV1BalanceSend for application/json ContentType.
type PostApiV1BalanceSendJSONRequestBody = SendRequest
